name: presenca
description: Your disciplines attendance helper.

publish_to: 'none'
version: 1.1.2

environment:
  sdk: ^3.0.1

dependencies:
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  csv: ^5.0.2
  dartz: ^0.10.1
  file_picker: ^5.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.1
  hive: ^2.1.0
  intl: ^0.18.0
  meta: ^1.7.0
  path: ^1.8.1
  path_provider: ^2.0.15
  share_plus: ^7.0.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.4.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.3

flutter:
  generate: true
  uses-material-design: true

flutter_icons:
  android: true
  image_path: assets/launcher_icons/foreground.png
  adaptive_icon_background: assets/launcher_icons/background.png
  adaptive_icon_foreground: assets/launcher_icons/foreground.png
