name: presenca
description: Your disciplines attendance helper.

publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  csv: ^5.0.1
  dartz: ^0.10.1
  file_picker: ^4.5.1
  file_saver: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.1
  hive: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  meta: ^1.7.0
  path_provider: ^2.0.9
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  json_serializable: ^6.1.5

dependency_overrides:
  file_saver:
    git:
      url: git@github.com:incrediblezayed/file_saver.git
      ref: c0ea84007896c6014c72785a8bcde0e9c53dc804

flutter:
  generate: true
  uses-material-design: true

flutter_icons:
  android: true
  image_path: assets/launcher_icons/foreground.png
  adaptive_icon_background: assets/launcher_icons/background.png
  adaptive_icon_foreground: assets/launcher_icons/foreground.png
