name: CD

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12.x"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs

      - run: flutter build apk --split-per-abi
      - run: flutter build appbundle

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/app/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/app-release.aab
